FractalDemo/Controllers/OrdenesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FractalDemo.Datos;
using FractalDemo.Models;
using FractalDemo.ViewModel;

namespace FractalDemo.Controllers
{
    public class OrdenesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdenesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Ordenes
        public IActionResult Index(string buscarOrden, int pagina = 1)
        {            
            var cantidadRegistrosPorPagina = 5;
                using (_context)
                {
                    var orders = _context.Ordenes.OrderBy(o => o.Orden_Id)
                        .Skip((pagina - 1) * cantidadRegistrosPorPagina)
                        .Take(cantidadRegistrosPorPagina).ToList();
                    var totalDeRegistros = _context.Productos.Count();

                    var modelo = new IndexVM();
                    modelo.Ordenes = orders;
                    modelo.PaginaActual = pagina;
                    modelo.TotalDeRegistros = totalDeRegistros;
                    modelo.RegistrosPorPagina = cantidadRegistrosPorPagina;

                    return View(modelo);
                }
            

        }

        public IActionResult IndexBuscar(string buscarOrden)
        {
            var Ordeness = from or in _context.Ordenes select or;
            if (!String.IsNullOrEmpty(buscarOrden))
            {
                Ordeness = Ordeness.Where(o => o.Cliente.Contains(buscarOrden));
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
            return View(Ordeness);
        }

        // GET: Ordenes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Ordenes == null)
            {
                return NotFound();
            }

            var orden = await _context.Ordenes
                .FirstOrDefaultAsync(m => m.Orden_Id == id);
            if (orden == null)
            {
                return NotFound();
            }

            return View(orden);
        }

        // GET: Ordenes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ordenes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Orden_Id,NumOrden,EstadoPedido,Cliente,Fecha,CantidadProducto,MontoInicial,IGV,MontoFinal")] Orden orden)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orden);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(orden);
        }

        // GET: Ordenes/Edit/5
        public IActionResult Edit(int id)
        {
            OrdenProductoVM ordenProductos = new OrdenProductoVM
            {
                ListaOrdenProductos = _context.OrdenProducto.Include(p => p.Producto).Include(o => o.Orden)
                .Where(o => o.Orden_Id == id),
                OrdenProducto = new OrdenProducto()
                {
                    Orden_Id = id
                },
                Orden = _context.Ordenes.FirstOrDefault(o => o.Orden_Id == id)
            };

            List<int> listaTemporalProductoOrdenes = ordenProductos.ListaOrdenProductos.Select(p => p.Producto_Id).ToList();
            var listaTemporal = _context.Productos.Where(p => !listaTemporalProductoOrdenes.Contains(p.Producto_Id)).ToList();
            ordenProductos.ListaProductos = listaTemporal.Select(i => new SelectListItem
            {
                Text = i.NombreProducto,
                Value = i.Producto_Id.ToString()
            });

            var mInicial = ordenProductos.Orden.MontoInicial;

            var cantidad = ordenProductos.Orden.CantidadProducto;

            return View(ordenProductos);
        }

        // POST: Ordenes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Orden_Id,NumOrden,EstadoPedido,Cliente,Fecha,CantidadProducto,MontoInicial,IGV,MontoFinal")] Orden orden)
        {
            if (id != orden.Orden_Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orden);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrdenExists(orden.Orden_Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(orden);
        }

        // GET: Ordenes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Ordenes == null)
            {
                return NotFound();
            }

            var orden = await _context.Ordenes
                .FirstOrDefaultAsync(m => m.Orden_Id == id);
            if (orden == null)
            {
                return NotFound();
            }

            return View(orden);
        }

        // POST: Ordenes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Ordenes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Ordenes'  is null.");
            }
            var orden = await _context.Ordenes.FindAsync(id);
            if (orden != null)
            {
                _context.Ordenes.Remove(orden);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public IActionResult AdministrarProductos(int id)
        {
            OrdenProductoVM ordenProductos = new OrdenProductoVM
            {
                ListaOrdenProductos = _context.OrdenProducto.Include(p => p.Producto).Include(o => o.Orden)
                .Where(o => o.Orden_Id == id),
                OrdenProducto = new OrdenProducto()
                {
                    Orden_Id = id
                },
                Orden = _context.Ordenes.FirstOrDefault(o => o.Orden_Id == id)
            };
            List<int> listaTemporalProductoOrdenes = ordenProductos.ListaOrdenProductos.Select(p => p.Producto_Id).ToList();
            var listaTemporal = _context.Productos.Where(p => !listaTemporalProductoOrdenes.Contains(p.Producto_Id)).ToList();
            ordenProductos.ListaProductos = listaTemporal.Select(i => new SelectListItem
            {
                Text = i.NombreProducto,
                Value = i.Producto_Id.ToString()
            });
            return View(ordenProductos);
        }
        [HttpPost]
        public IActionResult AdministrarProductos(OrdenProductoVM ordenProductos)
        {
                if (ordenProductos.OrdenProducto.Orden_Id != 0 && ordenProductos.OrdenProducto.Producto_Id != 0)
                {
                _context.OrdenProducto.Add(ordenProductos.OrdenProducto);
                //_context.Ordenes.Add(ordenProductos.Orden);
                //_context.Add(ordenProductos.Orden);
                    _context.SaveChanges();
                }
                return RedirectToAction(nameof(AdministrarProductos), new { @id = ordenProductos.Orden.Orden_Id });

            
        }

        [HttpPost]
        public IActionResult EliminarProductos(int idProducto, OrdenProductoVM ordenProductos)
        {
            int idOrden = ordenProductos.Orden.Orden_Id;
            OrdenProducto ordenProducto = _context.OrdenProducto.FirstOrDefault(
                    u => u.Producto_Id == idProducto && u.Orden_Id == idOrden
                );
                _context.OrdenProducto.Remove(ordenProducto);
                _context.SaveChanges();
            return RedirectToAction(nameof(Edit), new { @id = idOrden });
        }

        private bool OrdenExists(int id)
        {
          return (_context.Ordenes?.Any(e => e.Orden_Id == id)).GetValueOrDefault();
        }
    }
}

FractalDemo/Views/Ordenes/AdministrarProductos.cshtml
@model FractalDemo.ViewModel.OrdenProductoVM

@{
    ViewData["Title"] = "ProductManagment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-10">
        <h1>Add Product to  Order</h1>
    </div>
    <div class="col-2">
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-id="@Model.Orden.Orden_Id">Back to List</a>
    </div>
</div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="AdministrarProductos">
            <input type="hidden" asp-for="Orden.Orden_Id" />
            <input type="hidden" asp-for="OrdenProducto.Orden_Id" />

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Orden.Cliente" class="control-label" hidden></label>
                <input asp-for="Orden.Cliente" class="form-control" type="hidden"/>
            </div>

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="productos" class="control-label">Productos</label>
                @Html.DropDownListFor(u => u.OrdenProducto.Producto_Id, Model.ListaProductos, "--Seleccionar Productos--",
                new {@class = "form-control"})
            </div>

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Orden.CantidadProducto" class="control-label"></label>
                <input asp-for="Orden.CantidadProducto" class="form-control" />
            </div>

            <br />

            <div class="form-group">
                <input type="submit" value="Asociar Producto a Orden" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

    <br /><br />


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

FractalDemo/Views/Ordenes/Create.cshtml
@model FractalDemo.Models.Orden

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Orden</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumOrden" class="control-label"></label>
                <input asp-for="NumOrden" class="form-control" />
                <span asp-validation-for="NumOrden" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstadoPedido" class="control-label" hidden></label>
                <input asp-for="EstadoPedido" class="form-control" value="Pending" hidden/>
                <span asp-validation-for="EstadoPedido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cliente" class="control-label"></label>
                <input asp-for="Cliente" class="form-control" />
                <span asp-validation-for="Cliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <!--<div class="form-group">
                <label asp-for="MontoInicial" class="control-label"></label>
                <input asp-for="MontoInicial" class="form-control" />
                <span asp-validation-for="MontoInicial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IGV" class="control-label"></label>
                <input asp-for="IGV" class="form-control" />
                <span asp-validation-for="IGV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MontoFinal" class="control-label"></label>
                <input asp-for="MontoFinal" class="form-control" />
                <span asp-validation-for="MontoFinal" class="text-danger"></span>
            </div>-->

            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br /><br />
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FractalDemo/Views/Ordenes/Delete.cshtml
@model FractalDemo.Models.Orden

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Orden</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumOrden)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumOrden)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstadoPedido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstadoPedido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CantidadProducto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CantidadProducto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MontoInicial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MontoInicial)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IGV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IGV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MontoFinal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MontoFinal)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Orden_Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FractalDemo/Views/Ordenes/Details2.cshtml
@model FractalDemo.Models.Orden

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br><br />
<div>
        <div class="row">
            <div class="col-10">
                <h1>
                    Order
                    @Html.DisplayNameFor(model => model.NumOrden)
                    @Html.DisplayFor(model => model.NumOrden)
                </h1>
            </div>
            <div class="col-2">
                <a class="btn btn-secondary text-white" style="width:70%;" asp-action="Index">Back</a>
            </div>
        </div>
        
        <br />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstadoPedido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstadoPedido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
     </dl>

     <!--TABLA FALTA-->

     <div class="row">
         <div class="col-10"></div>
         <div class="col-2">
            <a class="btn btn-primary text-white" asp-action="AdministrarProductos" asp-route-id="@Model.Orden_Id">Add Item+</a>
         </div>
         </div>
    
     <div class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MontoInicial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MontoInicial)
        </dd>
        <dt class="col-sm-2">
            Taxes
        </dt>
        <dd class="col-sm-10"></dd>
        <dt class="col-sm-2">
            Total City Tax
        </dt>
        <dd class="col-sm-10">

        </dd>
        <dt class="col-sm-2">
            Total Country Tax
        </dt>
        <dd class="col-sm-10">

        </dd>
        <dt class="col-sm-2">
            Total State Tax
        </dt>
        <dd class="col-sm-10">

        </dd>
        <dt class="col-sm-2">
            Total Federal Tax
        </dt>
        <dd class="col-sm-10">

        </dd>
        <dt class = "col-sm-2">
            Total Taxes
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IGV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MontoFinal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MontoFinal)
        </dd>
    </div>
</div>

<div class="row">
    <div class="col-8"></div>
    <div class="col-4">

        <!-- INICIO COMPLETE ORDER -->
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Orden_Id" />
                    <div class="form-group">
                        <label asp-for="NumOrden" class="control-label"></label>
                        <input asp-for="NumOrden" class="form-control" />
                        <span asp-validation-for="NumOrden" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EstadoPedido" class="control-label"></label>
                        <select asp-for="EstadoPedido" class="form-control">
                            <option value="Pending">Pending</option>
                            <option value="Completed">Completed</option>
                            <option value="Rejected">Rejected</option>
                        </select>
                        <span asp-validation-for="EstadoPedido" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Cliente" class="control-label"></label>
                        <input asp-for="Cliente" class="form-control" />
                        <span asp-validation-for="Cliente" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Fecha" class="control-label"></label>
                        <input asp-for="Fecha" class="form-control" />
                        <span asp-validation-for="Fecha" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CantidadProducto" class="control-label"></label>
                        <input asp-for="CantidadProducto" class="form-control" />
                        <span asp-validation-for="CantidadProducto" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MontoInicial" class="control-label"></label>
                        <input asp-for="MontoInicial" class="form-control" />
                        <span asp-validation-for="MontoInicial" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="IGV" class="control-label"></label>
                        <input asp-for="IGV" class="form-control" />
                        <span asp-validation-for="IGV" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MontoFinal" class="control-label"></label>
                        <input asp-for="MontoFinal" class="form-control" />
                        <span asp-validation-for="MontoFinal" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Complete Order" class="btn btn-success text-white" style="width:145px; align-content:end;" />
                    </div>
                </form>
            </div>
        </div>
                        

        <!-- FINAL COMPLETE ORDER -->

        <a class="btn btn-success text-white" style="width:145px; align-content:end;" asp-action="">Complete Order</a>
        <a class="btn btn-danger text-white" style="width:130px;" asp-action="">Reject Order</a>
    </div>
</div>

FractalDemo/Views/Ordenes/Index.cshtml
@model FractalDemo.ViewModel.IndexVM

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Orders</h1>
<br />

<div class="row">
    <div class="col-10">
        @using (Html.BeginForm("IndexBuscar", "Ordenes",FormMethod.Post, null)){

            <p>
                ClientName: @Html.TextBox("buscarOrden")
                <input type="submit" value="Search">
            </p>
        }
    </div>
    <div class="col-2">
        <p align="right">
            <a class="btn btn-primary" asp-action="Create">Create Order</a>
        </p>
    </div>
</div>



<table class="table" style="text-align:center;">
    <thead style="background-color:lavender;">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Orden.NumOrden)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Orden.Cliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Orden.EstadoPedido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Orden.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Orden.MontoFinal)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Ordenes) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NumOrden)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cliente)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EstadoPedido)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
               @Html.DisplayFor(modelItem => item.MontoFinal)    
            </td>
            <td>
                <a style="text-decoration:none;" asp-action="Edit" asp-route-id="@item.Orden_Id">Edit</a>
            </td>
        </tr>
}
    </tbody>
</table>

@{
    Html.RenderPartial("_paginador", Model);
}

FractalDemo/Views/Ordenes/IndexBuscar.cshtml
@model IEnumerable<FractalDemo.Models.Orden>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Orders</h1>
<br />

<div class="row">
    <div class="col-10">
        @using (Html.BeginForm("IndexBuscar", "Ordenes", FormMethod.Post, null))
        {

            <p>
                ClientName: @Html.TextBox("buscarOrden")
                <input type="submit" value="Search">
            </p>
        }
    </div>
    <div class="col-2">
        <p align="right">
            <a class="btn btn-primary" asp-action="Create">Create Order</a>
        </p>
    </div>
</div>



<table class="table" style="text-align:center;">
    <thead style="background-color:lavender;">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumOrden)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstadoPedido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MontoFinal)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NumOrden)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cliente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EstadoPedido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MontoFinal)
                </td>
                <td>
                    <a style="text-decoration:none;" asp-action="Edit" asp-route-id="@item.Orden_Id">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>